<?php


/*
 * NuraWeb - Free and Open Source Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 *
 * LICENSE:
 * NuraWeb is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2024, Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@nurasoftware.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Str;
use App\Models\User;
use DB;
use File;

class AjaxController extends Controller
{
  
    /**
     * Search in registered users accounts
     */
    public function fetch(Request $request)
    {
        $source = $request->source;
        if (!$source) return null;

        $term = $request->input('term', '');
        if (empty($term)) {
            return array();
        }


        // Search in registered users accounts     
        if ($source == 'users') {
            $users = User::where('role', 'user')->whereNull('deleted_at')->where(function ($query) use ($term) {
                $query->where('name', 'like', "%$term%")
                    ->orwhere('email', 'like', "%$term%");
            })
                ->limit(25)->get(['id', DB::raw('CONCAT(`name`, " - ", `email`) AS text')]);
            return ['results' => $users];
        }


        // Search in internals
        if ($source == 'internals') {
            $users = User::where('role', 'internal')->whereNull('deleted_at')->where(function ($query) use ($term) {
                $query->where('name', 'like', "%$term%")
                    ->orwhere('email', 'like', "%$term%");
            })
                ->limit(25)->get(['id', DB::raw('CONCAT(`name`, " - ", `email`) AS text')]);
            return ['results' => $users];
        }


        // Search in admins
        if ($source == 'admins') {
            $users = User::where('role', 'admin')->whereNull('deleted_at')->where(function ($query) use ($term) {
                $query->where('name', 'like', "%$term%")
                    ->orwhere('email', 'like', "%$term%");
            })
                ->limit(25)->get(['id', DB::raw('CONCAT(`name`, " - ", `email`) AS text')]);
            return ['results' => $users];
        }


        // Search in internals and admins
        if ($source == 'internals_admins') {
            $users = User::whereNull('deleted_at')
                ->where(function ($query) {
                    $query->where('role', 'internal')
                        ->orwhere('role_id', 'admin');
                })
                ->where(function ($query) use ($term) {
                    $query->where('name', 'like', "%$term%")
                        ->orwhere('email', 'like', "%$term%");
                })
                ->limit(25)->get(['id', DB::raw('CONCAT(`name`, " - ", `email`) AS text')]);
            return ['results' => $users];
        }


        // Search in all accounts
        if ($source == 'accounts') {
            $users = User::whereNull('deleted_at')
                ->where(function ($query) use ($term) {
                    $query->where('name', 'like', "%$term%")
                        ->orwhere('email', 'like', "%$term%");
                })
                ->limit(25)->get(['id', DB::raw('CONCAT(`name`, " - ", `email`) AS text')]);
            return ['results' => $users];
        }


        // Search in active pages
        if ($source == 'pages') {
            $pages = DB::table('pages')
                ->leftJoin('pages_content', 'pages_content.page_id', '=', 'pages.id')
                ->select('pages.id as id', 'pages_content.title as text')
                ->where('pages_content.title', 'like', "%$term%")
                ->where('active', 1)
                ->limit(25)
                ->get(['id', 'title']);

            return ['results' => $pages];
        } // end if


        // Search in posts categories
        if ($source == 'posts_categ') {
            $posts_categories = DB::table('posts_categ')
                ->where('active', 1)
                ->where('title', 'like', "%$term%")
                ->limit(25)
                ->get(['id', DB::raw('CONCAT(`title`) AS text')]);

            return ['results' => $posts_categories];
        } // end if


        // Search in posts tags
        if ($source == 'posts_tags') {
            $term = trim($term);
            $array = array();

            $tags = DB::table('posts_tags')
                ->where('tag', 'like', "%$term%")
                ->orderBy('counter', 'desc')
                ->limit(25)
                ->get();

            foreach ($tags as $tag) {
                if (!in_array($tag->tag, $array))
                    array_push($array, $tag->tag);
            }

            return json_encode($array);
        } // end if



        // Search in active blocks
        if ($source == 'blocks') {
            $pages = DB::table('blocks')
                ->where('active', 1)
                ->where('label', 'like', "%$term%")
                ->limit(25)
                ->get(['id', DB::raw('CONCAT(`label`) AS text')]);

            return ['results' => $pages];
        } // end if


    }


    /**
     * Upload file from editor
     */
    public function editor_upload(Request $request)
    {

        if (!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') {
            $file = array_shift($_FILES);

            $file = $request->fileToUpload;
            $originalname = $file->getClientOriginalName();
            $new_filename = Str::random(12) . '-' . $originalname;
            $subfolder = date("Ym");
            if (!File::isDirectory('uploads' . DIRECTORY_SEPARATOR . $subfolder)) {
                File::makeDirectory('uploads' . DIRECTORY_SEPARATOR . $subfolder, 0777, true, true);
            }

            $path = 'uploads' . DIRECTORY_SEPARATOR . $subfolder . DIRECTORY_SEPARATOR . $new_filename;

            if (move_uploaded_file($file, $path)) {
                $data = array(
                    'success' => true,
                    'file'    => image($subfolder . DIRECTORY_SEPARATOR . $new_filename),
                );
            } else {
                $data = array(
                    'success' => false,
                    'message' => 'uploadError',
                );
            }

            //return $uploads_folder.DIRECTORY_SEPARATOR.$subfolder.DIRECTORY_SEPARATOR.$new_filename;

        } else {
            $data = array(
                'success' => false,
                'message' => 'uploadNotAjax',
                'formData' => $_POST
            );
        }

        return json_encode($data);
    }
}
