<?php

/*
 * NuraWeb - Free and Open Source Website Builder
 *
 * Copyright (C) 2024  Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 *
 * LICENSE:
 * NuraWeb is licensed under the GNU General Public License v3.0
 * Permissions of this strong copyleft license are conditioned on making available complete source code 
 * of licensed works and modifications, which include larger works using a licensed work, under the same license. 
 * Copyright and license notices must be preserved. Contributors provide an express grant of patent rights.
 *    
 * @copyright   Copyright (c) 2024, Chimilevschi Iosif Gabriel, https://nurasoftware.com.
 * @license     https://opensource.org/licenses/GPL-3.0  GPL-3.0 License.
 * @author      Chimilevschi Iosif Gabriel <office@nurasoftware.com>
 * 
 * 
 * IMPORTANT: DO NOT edit this file manually. All changes will be lost after software update.
 */

namespace App\Http\Controllers\Admin;

use App\Models\Config;
use App\Models\Upload;
use App\Models\ThemeFooterBlock;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;

class ThemeFooterController extends Controller
{


    /**
     * Edit footer
     */
    public function index()
    {
        return view('admin.index', [
            'view_file' => 'theme.config-footer',
            'active_menu' => 'theme',
            'active_submenu' => 'theme',
            'menu_section' => 'footer',
            'module' => 'footer',
        ]);
    }


    /**
     * Update theme
     */
    public function update(Request $request)
    {
        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        $inputs = $request->all();

        Config::update_config($inputs);

        return redirect(route('admin.theme.footer'))->with('success', 'updated');
    }


    /**
     * Edit footer content
     */
    public function content(Request $request)
    {
        return view('admin.index', [
            'view_file' => 'theme.config-footer-content',
            'active_menu' => 'theme',
            'active_submenu' => 'theme',
            'menu_section' => 'footer',
            'footer' => $request->footer,
        ]);
    }


    /**
     * Update footer content   
     */
    public function update_content(Request $request)
    {
        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        if (!($request->footer == 'primary' || $request->footer == 'secondary')) return redirect(route('admin.theme.footer'));

        $last_pos = themeFooterBlock::where('footer', $request->footer)->where('col', $request->col)->orderByDesc('position')->value('position');
        $position = ($last_pos ?? 0) + 1;

        if ($request->footer == 'primary') $layout = Config::config()->footer_columns ?? 1;
        if ($request->footer == 'secondary') $layout = Config::config()->footer2_columns ?? 1;

        $block = themeFooterBlock::create([
            'type' => $request->type,
            'footer' => $request->footer,
            'col' => $request->col, // column number
            'layout' => $layout, // number of columns
            'position' => $position,
        ]);

        return redirect(route('admin.theme.footer.block', ['id' => $block->id]));
    }


    /**
     * Remove the specified block content from footer
     */
    public function delete_content(Request $request)
    {
        // disable action in demo mode:
        if (config('app.demo_mode')) return redirect(route('admin'))->with('error', 'demo');

        if (!($request->footer)) return redirect(route('admin.theme.footer'));

        themeFooterBlock::where('id', $request->block_id)->delete();

        return redirect(route('admin.theme.footer.content', ['footer' => $request->footer]))->with('success', 'deleted');
    }


    /**
     * Ajax sortable footer blocks
     */
    public function sortable(Request $request)
    {
        $i = 0;

        if ($request->footer == 'primary') $layout = Config::config()->footer_columns ?? 1;
        if ($request->footer == 'secondary') $layout = Config::config()->footer2_columns ?? 1;

        $records = $request->all();

        foreach ($records['item'] as $key => $value) {

            themeFooterBlock::where('footer', $request->footer)
                ->where('col', $request->col)
                ->where('layout', $layout)
                ->where('id', $value)
                ->update([
                    'position' => $i,
                ]);

            $i++;
        }
    }


    /**
     * Show block
     */
    public function block(Request $request)
    {
        $block = themeFooterBlock::find($request->id);
        if (!$block) return redirect(route('admin'));

        return view('admin.index', [
            'view_file' => 'blocks.simple-blocks.' . $block->type,
            'active_menu' => 'theme',
            'menu_section' => 'footer',
            'block_module' => 'footer',
            'block' => $block,
            'is_footer_block' => 1,
            'referer' => request()->headers->get('referer'),
        ]);
    }



    /**
     * Update block    
     */
    public function block_update(Request $request)
    {
        // Simple text
        if ($request->type == 'text') {
            $text_title = $request['title'];
            $text_content = $request['content'];

            $content = array('title' => $text_title ?? null, 'content' => $text_content ?? null);
            $content = serialize($content);
            themeFooterBlock::where('id', $request->id)->update(['content' => $content]);
        }

        // Editor / Custom
        if ($request->type == 'editor' || $request->type == 'custom') {
            $content = $request['content'];
            themeFooterBlock::where('id', $request->id)->update(['content' => $content]);
        }

        // IMAGE      
        if ($request->type == 'image') {
            $image = null;
            if ($request->hasFile('image')) {
                $validator = Validator::make($request->all(), ['image' => 'file|image|max:5120']); // image mime, max 5 MB
                if (!$validator->fails())
                    $image = Upload::storeImage($request->file('image'), $oldImageCode = $request['existing_image'] ?? null, $data = array('module' => 'footer', 'item_id' => null, 'extra_item_id' => null));
            }
            $content = array('image' => $image->code ?? $request['existing_image'] ?? null, 'title' => $request['title'], 'caption' => $request['caption'], 'url' => $request['url']);
            $content = serialize($content);

            themeFooterBlock::where('id', $request->id)->update(['content' => $content]);
        }

        // LINKS
        if ($request->type == 'links') {
            $inputs = $request->except('_token');

            $post_key_title = 'a_title';
            $post_key_url = 'a_url';
            $post_key_icon = 'a_icon';
            $links_array_key = 'links_array';
            $links_array_key = array();
            $counter_key = 'numb_items';
            $counter_key = count(array_filter($_POST[$post_key_url]));

            for ($i = 0; $i < $counter_key; $i++) {
                if (!(empty(array_filter($_POST[$post_key_title])) && empty(array_filter($_POST[$post_key_url]))))
                    $links_array_key[$i] = array('title' => $inputs["$post_key_title"][$i], 'url' => $inputs["$post_key_url"][$i], 'icon' => $inputs["$post_key_icon"][$i]);
            }
            $content = serialize($links_array_key);

            // header data
            $header_array = array();
            if ($request->add_header ?? null) {
                $header_array = array('add_header' => 'on', 'title' => $request->header_title, 'content' =>  $request->header_content);
                $header_content = serialize($header_array);
            }

            // extra
            $block_extra = array('new_tab' => $request->new_tab ?? null, 'display_style' => $request->display_style);

            themeFooterBlock::where('id', $request->id)->update(['content' => $content ?? null, 'header' => $header_content ?? null, 'extra' => serialize($block_extra) ?? null]);
        }



        // Extra content ALERT 
        if ($request->type == 'image') {
            $block_extra = array('shaddow' => $request->shaddow ?? null);
            themeFooterBlock::where('id', $request->id)->update(['extra' => serialize($block_extra)]);
        }


        // Extra content MAP       
        if ($request->type == 'map') {
            $block_extra = array('height' => $request->height ?? 400, 'zoom' => $request->zoom ?? 16, 'address' => $request->address);
            themeFooterBlock::where('id', $request->id)->update(['extra' => serialize($block_extra)]);
        }


        // ***************************************************
        // Block CONTENT
        // ***************************************************
        /*
        $langs = SysLang::getLangs();

        $inputs = $request->except('_token');

        // UPDATE CONTENT
        foreach ($langs as $lang) {
            $content = null;

          
         


            // LINKS
            if ($request->type == 'links') {
                $post_key_title = 'a_title_' . $lang->id;
                $post_key_url = 'a_url_' . $lang->id;
                $post_key_icon = 'a_icon_' . $lang->id;
                $links_array_key = 'links_array_' . $lang->id;
                $links_array_key = array();
                $counter_key = 'numb_items_' . $lang->id;
                $counter_key = count(array_filter($_POST[$post_key_url]));

                for ($i = 0; $i < $counter_key; $i++) {
                    if (!(empty(array_filter($_POST[$post_key_title])) && empty(array_filter($_POST[$post_key_url]))))
                        $links_array_key[$i] = array('title' => $inputs["$post_key_title"][$i], 'url' => $inputs["$post_key_url"][$i], 'icon' => $inputs["$post_key_icon"][$i]);
                }
                $content = serialize($links_array_key);
                themeFooterBlockContent::updateOrInsert(['block_id' => $request->id, 'lang_id' => $lang->id], ['content' => $content]);

                // header data
                $header_array = array();
                if ($inputs['add_header_' . $lang->id] ?? null) {
                    $header_array = array('add_header' => 'on', 'title' => $inputs["header_title_$lang->id"], 'content' =>  $inputs["header_content_$lang->id"]);
                    $header_content = serialize($header_array);
                    themeFooterBlockContent::where(['block_id' => $request->id, 'lang_id' => $lang->id])->update(['header' => $header_content]);
                }
            }
        } // end langs
        */

        if ($request->hide ?? null) $hide = 1;
        themeFooterBlock::where('id', $request->id)->update(['label' =>  $request->label ?? null,  'hide' => $hide ?? 0, 'updated_at' => now()]);

        if ($request->referer) return redirect($request->referer)->with('success', 'updated');
        else return redirect(route('admin.theme.footer'))->with('success', 'updated');
    }
}
